### ISSUE TITLE
Ds Store?

### ISSUE THREAD

**Issue by camila-rahal** [UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica#1]
Why is this created with almost every file? "DS Store". Can I delete it?
@DeAngelisA 

<img width="1433" alt="Screenshot 2024-03-26 at 15 34 49" src="https://github.com/UniLuFS2020-ReplicationSeminar/Groupwork_Camila_Jessica/assets/121042379/cd800e70-35ac-4dfa-9365-042c8a7c965e">

**Comment by DeAngelisA** [comment]
@camila-rahal : yes, this is an internal MacOS function that is completely irrelevant and can be deleted. All Mac users experience this. You can [add it to the gitignore file](https://stackoverflow.com/a/76942565/2590617).

**Comment by camila-rahal** [comment]
> @camila-rahal : yes, this is an internal MacOS function that is completely irrelevant and can be deleted. All Mac users experience this. You can [add it to the gitignore file](https://stackoverflow.com/a/76942565/2590617).
 
 It worked. Thank you.
